//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainWebApplication.Member {
    
    
    public partial class Events {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new MainWebApplication.mpDefault Master {
            get {
                return ((MainWebApplication.mpDefault)(base.Master));
            }
        }
    }
}
